### ISSUE TITLE
Weaver Components should use Ngrx to to maintain state.

### ISSUE THREAD

**Issue by jeremythuff** [TAMULib/weaver-components#364]
Components should be analyzed for self-handled state storage in class-level properties. Any such instance should be identified as a candidate for NGRX and an issue created for them.

The created issues should provide a suggestion for the nature of the store used to hold the redux state.

**Comment by wwelling** [comment]
1. Investigate Manifest component to avoid maintaining local state of children manifest entry components. #389
2. Card component needs redesign to avoid local state from DOM inspection #387
3. Theme service should reference store instead of copying #384
4. Layout should have configurable breakpoints #383
5. Create action store to perform arbitrary actions #386
6. Create alert store and redesign alert component to be backed by the store #385
7. Create Component Entity Store #332

Refactor Template Service to Template Utility #379
Colors in color utility should be brought in via JSON #390
Refactor mobile store to layout store #382
